# Generated by Django 5.0.14 on 2026-01-13 23:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('clio', 'Clio'), ('mycase', 'MyCase'), ('quickbooks', 'QuickBooks')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Token Expired'), ('revoked', 'Revoked'), ('error', 'Error')], default='pending', max_length=20)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_user_id', models.CharField(blank=True, max_length=255)),
                ('provider_account_id', models.CharField(blank=True, max_length=255)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.firm')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('firm', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('display_number', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('client_name', models.CharField(max_length=255)),
                ('client_external_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='open', max_length=50)),
                ('practice_area', models.CharField(blank=True, max_length=100)),
                ('billing_method', models.CharField(blank=True, max_length=50)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='accounts.firm')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matters', to='integrations.integration')),
            ],
            options={
                'ordering': ['client_name', 'display_number'],
                'unique_together': {('integration', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('timekeeper_name', models.CharField(max_length=255)),
                ('timekeeper_external_id', models.CharField(blank=True, max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('billed', models.BooleanField(default=False)),
                ('billable', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='accounts.firm')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='integrations.integration')),
                ('matter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='integrations.matter')),
            ],
            options={
                'ordering': ['-date', 'timekeeper_name'],
                'unique_together': {('integration', 'external_id')},
            },
        ),
    ]
