# Generated by Django 5.0.14 on 2026-01-13 23:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='invoices/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=1)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('matter_number', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('billing_attorney', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retainer_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('extracted', 'Data Extracted'), ('review', 'Needs Review'), ('confirmed', 'Confirmed'), ('error', 'Processing Error')], default='pending', max_length=20)),
                ('extraction_confidence', models.FloatField(default=0.0)),
                ('raw_extraction', models.JSONField(blank=True, default=dict)),
                ('extraction_notes', models.TextField(blank=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.firm')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('timekeeper', models.CharField(blank=True, max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_type', models.CharField(choices=[('time', 'Time Entry'), ('expense', 'Expense'), ('flat_fee', 'Flat Fee'), ('other', 'Other')], default='time', max_length=20)),
                ('matched', models.BooleanField(default=False)),
                ('matched_time_entry_id', models.CharField(blank=True, max_length=100)),
                ('line_number', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
            ],
            options={
                'ordering': ['invoice', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceProcessingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('api_tokens_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
